select
    StartUtc as start_utc,
    EndUtc as end_utc,
    CreatedUtc as created_utc,
    NightCount as night_count,
    NightCost_Sum as night_cost_sum,
    OccupiedSpace_Sum as occupied_space_sum,
    GuestCount_Sum as guest_count_sum,
    LeadTime as lead_time,
    StayLength as stay_length,
    CancellationReason as cancellation_reason,
    SettlementType as settlement_type,
    ReservationState as reservation_state,
    Origin as origin,
    CommanderOrigin as commander_origin,
    TravelAgency as travel_agency,
    IsOnlineCheckin as is_online_checkin,
    NationalityCode as nationality_code,
    Gender as gender,
    Classification as classification,
    AgeGroup as age_group,
    HasEmail as has_email,
    EnterpriseTimeZone as enterprise_time_zone,
    BusinessSegment as business_segment,
    Tier as tier,
    RateId as rate_id
FROM hotel.reservations